apiVersion: apps/v1
kind: Deployment
metadata:
   name: agile-singledb-front-postgress-testing
   namespace: nodejstesting
spec:
   replicas: 1
   selector:
     matchLabels:
       app: agile-singledb-front-postgress-testing-app
   template:
      metadata:
        labels:
          app: agile-singledb-front-postgress-testing-app
      spec:
        
        containers:
        - image: docker-registry-server:5000/agile-singledb-node-front-postgress-testing:tagVersion
          name: agile-singledb-front-postgress-testing-cont
          resources:
                  requests:
                          memory: "1Mi"
                          cpu: "0.1"
                  limits:
                          memory: "1000Mi"
                          cpu: "0.7"
          

---
apiVersion: v1
kind: Service
metadata:
  name: agile-singledb-front-postgress-testing-svc
  namespace: nodejstesting
spec:
  selector:
     app: agile-singledb-front-postgress-testing-app
  type: NodePort
  ports:
    - nodePort: 31169
      port: 5000
      targetPort: 5000
      
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: agile-singledb-front-postgress-testing-autoscale
  namespace: nodejsprod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: agile-singledb-front-postgress-testing
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
